### ISSUE TITLE
Won't generate

### ISSUE THREAD

**Issue by hobolyra** [JumpingCoconut/Elrond-stable-diffusion-webui-discord#3]
sadly I can't get this to work, it connects with the WebUI, the bot logs in, commands show up, but when I actually go to generate:

```
Task exception was never retrieved
future: <Task finished name='Task-36' coro=<draw() done, defined at C:\Botshit\Elrond-stable-diffusion-webui-discord\venv\lib\site-packages\interactions\client\models\command.py:899> exception=AttributeError('red')>
Traceback (most recent call last):
  File "C:\Botshit\Elrond-stable-diffusion-webui-discord\venv\lib\site-packages\interactions\client\models\command.py", line 941, in wrapper
    raise e
  File "C:\Botshit\Elrond-stable-diffusion-webui-discord\venv\lib\site-packages\interactions\client\models\command.py", line 910, in wrapper
    return await coro(ctx, *args, **kwargs)
  File "C:\Botshit\Elrond-stable-diffusion-webui-discord\elrond.py", line 422, in draw
    await draw_image(ctx=ctx, prompt=prompt, seed=seed, quantity=quantity, negative_prompt=negative_prompt, img2img_url=img2img_url, denoising_strength=denoising_strength, host=host_url)
  File "C:\Botshit\Elrond-stable-diffusion-webui-discord\elrond.py", line 220, in draw_image
    color=assign_color_to_user(ctx.user.username),
  File "C:\Botshit\Elrond-stable-diffusion-webui-discord\elrond.py", line 145, in assign_color_to_user
    color = interactions.Color.red() # Default
  File "C:\Program Files\Python310\lib\enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: red
```

**Comment by JumpingCoconut** [comment]
Thanks for the info! The SD-Webui has changed a bit so I had to update Elrond too. Try to update, should work now. If it doesnt work, please let me know. Either comment here or open a new issue.

**Comment by hobolyra** [comment]
> Thanks for the info! The SD-Webui has changed a bit so I had to update Elrond too. Try to update, should work now. If it doesnt work, please let me know. Either comment here or open a new issue.

I know it's not the token/connection as I can get another Discord bot working fine with Automatic1111 right now, but for some reason this one even updated (I just completely deleted and recloned) still throws this out when generating: (I included the loaded message to show it did indeed connect, and shows up in discord as well)

```
C:\Stable Diffusion\DISCORD\Elrond-stable-diffusion-webui-discord>elrond.py
Waiting for webui http://localhost:7860 to start...Bot is running!
Task exception was never retrieved
future: <Task finished name='Task-22' coro=<draw() done, defined at C:\Users\HoboLyra\AppData\Roaming\Python\Python310\site-packages\interactions\client\models\command.py:899> exception=AttributeError('red')>
Traceback (most recent call last):
  File "C:\Users\HoboLyra\AppData\Roaming\Python\Python310\site-packages\interactions\client\models\command.py", line 941, in wrapper
    raise e
  File "C:\Users\HoboLyra\AppData\Roaming\Python\Python310\site-packages\interactions\client\models\command.py", line 910, in wrapper
    return await coro(ctx, *args, **kwargs)
  File "C:\Stable Diffusion\DISCORD\Elrond-stable-diffusion-webui-discord\elrond.py", line 422, in draw
    await draw_image(ctx=ctx, prompt=prompt, seed=seed, quantity=quantity, negative_prompt=negative_prompt, img2img_url=img2img_url, denoising_strength=denoising_strength, host=host_url)
  File "C:\Stable Diffusion\DISCORD\Elrond-stable-diffusion-webui-discord\elrond.py", line 220, in draw_image
    color=assign_color_to_user(ctx.user.username),
  File "C:\Stable Diffusion\DISCORD\Elrond-stable-diffusion-webui-discord\elrond.py", line 145, in assign_color_to_user
    color = interactions.Color.red() # Default
  File "C:\Program Files\Python310\lib\enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: red
```

**Comment by JumpingCoconut** [comment]
Did you run install.bat first? It seems the bot is missing discord interactions library as it can't find the discord color "red". Try running install.bat and then the start-discordbot.bat

**Comment by Goob-bi** [comment]
i fixed the error by changing the color codes
> interactions.Color.red()

to
> interactions.Color.RED

the result is this

> def assign_color_to_user(username):
        username_as_color_int = int(ord(username[0])) % 7
        color = interactions.Color.RED # Default
        if username_as_color_int == 0: 
            color = interactions.Color.BLURPLE
        elif username_as_color_int == 1: 
            color = interactions.Color.GREEN
        elif username_as_color_int == 2: 
            color = interactions.Color.YELLOW
        elif username_as_color_int == 3: 
            color = interactions.Color.FUCHSIA
        elif username_as_color_int == 4: 
            color = interactions.Color.RED
        elif username_as_color_int == 5: 
            color = interactions.Color.WHITE
        elif username_as_color_int == 6: 
            color = interactions.Color.BLACK
        return color
